[package]
name = "bitwig-registry"
description = "Resolving and reading Bitwig's internal content registry"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-only"
repository.workspace = true

[dependencies]
bitwig-classfile.workspace = true
bitwig-document.workspace = true
krakatau2.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
bitwig-install.workspace = true
